# Site settings
title: XperiCode Blog
email: mwijnands@xpericode.com
description: > # this means to ignore newlines until "baseurl:"
  A programming blog by Marcel Wijnands. XperiCode is the pseudo company name.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.xpericode.com" # the base hostname & protocol for your site
twitter_username: m_wijnands
github_username:  mwijnands
stackoverflow_username: mwijnands
stackoverflow_userid: 503050

# Build settings
markdown: kramdown
